apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine # Using the same Redis image
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis # Service name used by the Flask app
spec:
  type: ClusterIP # Internal service type
  selector:
    app: redis # Selects pods with label "app: redis"
  ports:
  - protocol: TCP
    port: 6379      # Port the service listens on
    targetPort: 6379 # Port the container listens on